name: apni_dukaan_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  hooks_riverpod: ^0.14.0+1
  flutter_hooks: ^0.16.0

  # google
  google_fonts: ^2.0.0

  # location
  google_maps_flutter: ^2.0.3
  location: ^4.1.1
  geolocator: ^7.0.3
  location_permissions: ^3.0.0+1
  permission_handler: ^7.1.0

  # ui
  flutter_vector_icons: ^1.0.0
  badges: ^2.0.0-nullsafety.1
  auto_size_text: ^3.0.0-nullsafety.0
  carousel_slider: ^4.0.0-nullsafety.0
  scrollable_positioned_list: ^0.2.0-nullsafety.0
  font_awesome_flutter: ^9.0.0
  simple_animations: ^3.1.1

  # utils
  flutter_screenutil: ^5.0.0
  flutter_dotenv: ^4.0.0-nullsafety.1
  uuid: ^3.0.4
#  camera: ^0.8.1
  equatable: ^2.0.0
  supercharged: ^2.0.0

  # internationalization
  intl: ^0.17.0

  # file management
  path_provider: ^2.0.1
  image_picker: ^0.7.4

  # http
  dio: ^4.0.0

  # storage
  sembast: ^3.0.1
  shared_preferences: ^2.0.5

  # routing
  beamer: ^0.12.4
  url_launcher: ^6.0.3

  # backend
  appwrite: ^0.5.0-dev.1

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
